spring.application.name=lostFoundService

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/lost_found_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:6511/eureka/
eureka.instance.prefer-ip-address=true

# Server Configuration
server.port=8086

# Error Configuration
server.error.include-message=always

# Actuator exposure
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Increase Max HTTP Post Size (for large Base64 images)
#server.tomcat.max-http-post-size=10MB

# Lost & Found image configuration
lostfound.image.base-url=http://localhost:9092/api/lost-found/images
lostfound.image.storage-path=./uploads/lostfound

# Multipart upload limits
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# AI Similarity Service
ai.similarity.url=${AI_SIMILARITY_URL:http://localhost:8000}
